version: 2

references:
  workspace: &workspace
               ~/sticky-sessions-android

  config_android: &config_android
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JAVA_TOOL_OPTIONS: "-Xms1024m -Xmx3200m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2"

  config_gcloud: &config_gcloud
    working_directory: *workspace
    docker:
      - image: google/cloud-sdk:latest
    environment:
      TERM: dumb

  cache_key: &cache_key
    key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: .
      paths:
        - app/build
        - ftl-tests
        - fastlane
        - Gemfile

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace

jobs:
  build:
    <<: *config_android

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true

      - run:
          name: Store Prod Firebase Key
          command: echo $GOOGLE_SERVICES_PROD | base64 -di > ~/sticky-sessions-android/app/src/prod/google-services.json

      - run:
          name: Store Stag Firebase Key
          command: echo $GOOGLE_SERVICES_STAG | base64 -di > ~/sticky-sessions-android/app/src/stag/google-services.json

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle

      - run:
          name: Build
          command: ./gradlew clean assembleProd assembleStag assembleProdDebugAndroidTest --stacktrace

      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/

      - run:
          name: Run Lint and Unit tests
          command: ./gradlew lintProdRelease testProdReleaseUnitTest

      - store_test_results:
          path: app/build/test-results

      - run:
          name: Generate Code Coverage report
          command: ./gradlew jacocoStagDebugReport

      - store_artifacts:
          path: app/build/reports/jacoco/jacocoStagDebugReport
          destination: coverage-report

      - run:
          name: Upload Code Coverage report to Coveralls
          command: ./gradlew coveralls

      - *persist_to_workspace

  test_instrumented:
    <<: *config_gcloud

    steps:
      - *attach_workspace

      - run:
          name: Setup Google Cloud auth
          command: ftl-tests/setup.sh

      - run:
          name: Run tests on Firebase Test Lab
          command: ftl-tests/run-tests.sh

  deploy_to_firebase:
    <<: *config_android

    steps:
      - *attach_workspace

      - run:
          name: Install fastlane
          command: bundle install

      - run:
          name: Install Firebase CLI
          command: |
            curl -sL firebase.tools | bash

      - run:
          name: Deploy stag app to firebase distribution
          command: |
            bundle exec fastlane distribute app_id:$FIREBASE_APP_ID_STAG apk_path:$APK_PATH_STAG firebase_token:$FIREBASE_TOKEN testers:$STAG_TESTERS

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test_instrumented:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy_to_firebase:
          requires:
            - build
          filters:
            branches:
              only:
                - master
